---
title: "hw_1"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r, message=FALSE}
library(tidyverse)
theme_set(theme_bw())
```

## task 1.1

Дан график логнормального распределения со средним 3 и стандартным отклонением 0.5. Используйте функцию `integrate()`, чтобы посчитать закрашенную площадь под кривой.

```{r}
shade <- tibble(x = qlnorm(10:90/100, mean = 3, sd = 0.5),
                    PDF = dlnorm(x = x, mean = 3, sd = 0.5))
tibble(x = 1:100,
       PDF = dlnorm(x = x, mean = 3, sd = 0.5)) %>% 
  ggplot(aes(x, PDF))+
  geom_line()+
  geom_area(data = shade, aes(x, PDF), fill = "lightblue")+
  geom_vline(xintercept = qlnorm(0.1, mean = 3, sd = 0.5), linetype = 2)+
  geom_vline(xintercept = qlnorm(0.9, mean = 3, sd = 0.5), linetype = 2)+
  labs(title = "PDF логнормального распределения (μ = 3, sd = 0.5)")+
  annotate(geom = "text", y = 0.04, x = c(3, 31), label = c("10%\n квантиль", "90%\n квантиль"), color = "red")
ggsave("task_1.1.png", device = "png")
```

```{r}
integrate(function(x){dlnorm(x, 3, 0.5)}, 
          qlnorm(0.1, mean = 3, sd = 0.5), 
          qlnorm(0.9, mean = 3, sd = 0.5))$value %>% 
  round(3)
```

## task 1.2

```{r}
p <- seq(0, 1, by = 0.01)
tibble(p) %>% 
  ggplot(aes(p)) +
  stat_function(fun = function(p) dbinom(9, 9+7, p)*dbinom(38, 38+6, p))+
  labs(x = "оценка биномиальным распределением вероятности слова бабочка быть класса b",
       y = "значение функции правдоподобия\n(два эксперимента)")
ggsave("task_1.2.png", device = "png")

p[which.max(dbinom(9, 9+7, p)*dbinom(38, 38+6, p))]
```

## task 1.3

```{r}
read_csv("https://afbo.info/pairs.csv?sEcho=1&iSortingCols=1&iSortCol_0=0&sSortDir_0=asc") %>% 
  filter(reliability == "high") ->
  afbo_filtered

library(fitdistrplus)
exp <- fitdist(afbo_filtered$count_borrowed, distr = "exp", method = "mle")
pois <- fitdist(afbo_filtered$count_borrowed, distr = "pois", method = "mle")

afbo_filtered %>% 
  ggplot(aes(count_borrowed))+
  geom_histogram(aes(y = ..density..))+
  stat_function(fun = dexp, args = exp$estimate, color = "red")+
  labs(caption = "data from afbo.info")
ggsave("task_1.3.png", device = "png")
```
